### ISSUE TITLE
Nesting tabs

### ISSUE THREAD

**Issue by custa1200** [simonsmith/jquery.herotabs#10]
When I nest tabs I get the following error in the console.

```
TypeError: $('.admin__tabs--projects').herotabs is not a function. (In '$('.admin__tabs--projects').herotabs', '$('.admin__tabs--projects').herotabs' is undefined)
```

Is it not possible to nest tabs?

**Comment by simonsmith** [comment]
Have you got an example that can demonstrate the error?

**Comment by simonsmith** [comment]
Looks to me just from that error that you don't have the plugin loaded.

**Comment by custa1200** [comment]
The outer set work ok so the plugin is loading . I'll try to strip down an example to show.

**Comment by custa1200** [comment]
```
<section class="section admin__continer">
    <div class="tabs tabs--horizontal admin__tabs--admin">
        <nav class="tabs__list tabs--horizontal__list">
          <ul class="tabs__tabs">
              <li class="tabs__tab tabs--horizontal__tab"><a href="#tab--users" class="tabs__link tabs--horizontal__link">Users</a></li>
              <li class="tabs__tab tabs--horizontal__tab"><a href="#tab--projects" class="tabs__link tabs--horizontal__link">Projects</a></li>
              <li class="tabs__tab tabs--horizontal__tab"><a href="#tab--data" class="tabs__link tabs--horizontal__link">Data</a></li>
          </ul>
        </nav>
        <div class="tabs__content tabs--horizontal__content">
          <div class="tabs__panel tabs--horizontal__panel tabs--horizontal__panel--current" id="tab--users">
              Users
          </div>
          <div class="tabs__panel tabs--horizontal__panel" id="tab--projects">
            <section class="section admin__projects">
              <div class="admin__container__projects">
                <div class="tabs tabs--vertical admin__tabs--projects">
                  <nav class="tabs__list tabs--vertical__list">
                    <ul class="tabs__tabs">
                    <li class="tabs--vertical__tab"><a href="#tab--project__info" class="tabs__link tabs--vertical__link">Info</a></li>
                      <li class="tabs--vertical__tab"><a href="#tab--project__sections" class="tabs__link tabs--vertical__link">Section</a></li>
                    </ul>
                  </nav>
                  <div class="tabs__content tabs--vertical__content">
                    <div id="tab--project__info" class="tabs__panel tabs--vertical__panel">
                      Info
                    </div>
                    <div id="tab--project__sections" class="tabs__panel tabs--vertical__panel">
                      Section
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
          <div class="tabs__panel tabs--horizontal__panel" id="tab--data">
              Data
          </div>
        </div>
    </div>
</section>

<script src="/bower_components/jquery.herotabs/dist/jquery.herotabs.js"></script>
<script>
$('.admin__tabs--admin').herotabs({
  duration: 200,
  easing: "ease-out",
  css: {
    active: "tabs__active",
    navCurrent: "tabs--horizontal__tab--active",
    current: "tabs--horizontal__panel--current",
  },
  selectors: {
    tab: ".tabs__panel",
    nav: ".tabs__tabs",
    navItem: ".tabs__tab"
  },
  useTouch: true,
  startOn: 0
});
$('.admin__tabs--projects').herotabs({
  css: {
    active: "tabs__active",
    navCurrent: "tabs--horizontal__tab--active",
    current: "tabs--horizontal__panel--current",
  },
  selectors: {
    tab: ".tabs__panel",
    nav: ".tabs__tabs",
    navItem: ".tabs__tab"
  },
  useTouch: true,
  startOn: 0
});
<script>
```

**Comment by custa1200** [comment]
this is my CSS too...
``` css
<style>
.tabs__tabs{margin:0;padding:0;list-style-type:none}.tabs--horizontal{margin:0 1.6875rem}.tabs--horizontal__list{vertical-align:top;padding:0;margin:0;z-index:0;display:block;border-bottom:3px solid #ddd}.tabs--horizontal__list ul,.tabs--horizontal__tab{padding:0;display:inline-block;vertical-align:top}.tabs--horizontal__list ul{list-style-type:none;margin:0;z-index:0}.tabs--horizontal__tab{margin:0 .84375rem;float:left;position:relative;top:3px;font-size:1.5625rem}.tabs--horizontal__tab--active{z-index:100}.tabs--horizontal__tab--active:after,.tabs--horizontal__tab--active:before{content:"";position:absolute;width:50%;bottom:0;border-bottom:3px solid #6443a4}.tabs--horizontal__tab--active:before{left:0}.tabs--horizontal__tab--active:after{left:50%}.tabs--horizontal__link{display:block;padding:.84375rem 0;text-decoration:none}.tabs--horizontal__link:active,.tabs--horizontal__link:focus,.tabs--horizontal__link:hover,.tabs--horizontal__link:link,.tabs--horizontal__link:visited{color:#333;text-decoration:none;outline:0}.tabs--horizontal__link:active,.tabs--horizontal__link:focus,.tabs--horizontal__link:hover{color:#6443a4}.tabs--horizontal__content{display:block;width:100%}.tabs--horizontal__panel:after,.tabs--horizontal__panel:before{content:'';display:table}.tabs--horizontal__panel{-webkit-transform:scale(0)!important;-ms-transform:scale(0)!important;transform:scale(0)!important;-webkit-transition:.2s!important;transition:.2s!important;width:100%;margin:1.6875rem 0}.tabs--horizontal__panel:after{clear:both}.tabs--horizontal__panel--current{-webkit-transform:scale(1)!important;-ms-transform:scale(1)!important;transform:scale(1)!important}.tabs--vertical__list{vertical-align:top;padding:0;margin:0;z-index:0;width:calc(99.99% * 1/4 - (30px - 30px * 1/4))}.tabs--vertical__list:nth-child(n){float:left;margin-right:30px;clear:none}.tabs--vertical__list:last-child,.tabs--vertical__list:nth-child(4n){margin-right:0}.tabs--vertical__list:nth-child(4n+1){clear:left}.tabs--vertical__tab{padding:0;margin:0;display:block;vertical-align:top;position:relative;top:3px;font-size:1.5625rem;text-align:center;background-color:#fff}.tabs--vertical__tab--active{z-index:100;font-weight:400;background-color:#fff}.tabs--vertical__tab--active:after,.tabs--vertical__tab--active:before{content:"";position:absolute;width:50%;bottom:0;border-bottom:3px solid #6443a4}.tabs--vertical__tab--active:before{left:0}.tabs--vertical__tab--active:after{left:50%}.tabs--vertical__link{display:block;padding:.84375rem;text-decoration:none}.tabs--vertical__link:active,.tabs--vertical__link:focus,.tabs--vertical__link:hover,.tabs--vertical__link:link,.tabs--vertical__link:visited{color:#333;text-decoration:none;outline:0}.tabs--vertical__link:active,.tabs--vertical__link:focus,.tabs--vertical__link:hover{color:#6443a4}.tabs--vertical__content{display:block;width:calc(99.99% * 3/4 - (30px - 30px * 3/4))}.tabs--vertical__panel:after,.tabs--vertical__panel:before{content:'';display:table}.tabs--vertical__content:nth-child(n){float:left;margin-right:30px;clear:none}.tabs--vertical__content:last-child,.tabs--vertical__content:nth-child(4n){margin-right:0}.tabs--vertical__content:nth-child(4n+1){clear:left}.tabs--vertical__panel{-webkit-transform:scale(0)!important;-ms-transform:scale(0)!important;transform:scale(0)!important;-webkit-transition:.2s!important;transition:.2s!important;width:100%;background:#fff}.tabs--vertical__panel:after{clear:both}.tabs--vertical__panel--current{-webkit-transform:scale(1)!important;-ms-transform:scale(1)!important;transform:scale(1)!important}


</style>
```

**Comment by simonsmith** [comment]
Have recreated your demo in this JSBin - http://jsbin.com/dudexe/edit?html,js,output

Not seeing any JS errors. Can you take a look and see if that's working as expected?

**Comment by custa1200** [comment]
If I click on info or section under Projects it does not show the respective tab

**Comment by simonsmith** [comment]
I think you may have an issue with your CSS as the same bug is present if I only run the plugin on the `.admin__tabs--admin` block of HTML (http://jsbin.com/dudexe/edit?html,js,output). Perhaps simplify your CSS to simple show/hide and add the animations once it is working correctly.

But for now I don't see an issue with Herotabs itself

**Comment by custa1200** [comment]
I removed the transitions and just reverted back to block/none, but the issue still exists that the nested  tabs under Projects (i.e. Info and Sections) do not get created (.admin__tabs--projects) and if I click on Projects, then click sections, instead of showing the Sections tab under Projects if then just shows the Data tab which is a sibling of the parent Projects. It's as if they are never created  
```css
.tabs__tabs{margin:0;padding:0;list-style-type:none}.tabs--horizontal{margin:0 1.6875rem}.tabs--horizontal__list{vertical-align:top;padding:0;margin:0;z-index:0;display:block;border-bottom:3px solid #ddd}.tabs--horizontal__list ul,.tabs--horizontal__tab{padding:0;display:inline-block;vertical-align:top}.tabs--horizontal__list ul{list-style-type:none;margin:0;z-index:0}.tabs--horizontal__tab{margin:0 .84375rem;float:left;position:relative;top:3px;font-size:1.5625rem}.tabs--horizontal__tab--active{z-index:100}.tabs--horizontal__tab--active:after,.tabs--horizontal__tab--active:before{content:"";position:absolute;width:50%;bottom:0;border-bottom:3px solid #6443a4}.tabs--horizontal__tab--active:before{left:0}.tabs--horizontal__tab--active:after{left:50%}.tabs--horizontal__link{display:block;padding:.84375rem 0;text-decoration:none}.tabs--horizontal__link:active,.tabs--horizontal__link:focus,.tabs--horizontal__link:hover,.tabs--horizontal__link:link,.tabs--horizontal__link:visited{color:#333;text-decoration:none;outline:0}.tabs--horizontal__link:active,.tabs--horizontal__link:focus,.tabs--horizontal__link:hover{color:#6443a4}.tabs--horizontal__content{display:block;width:100%}.tabs--horizontal__panel{width:100%;margin:1.6875rem 0;display:none}.tabs--horizontal__panel:after,.tabs--horizontal__panel:before{content:'';display:table}.tabs--horizontal__panel:after{clear:both}.tabs--horizontal__panel--current{display:block}.tabs--vertical__list{vertical-align:top;padding:0;margin:0;z-index:0;width:calc(99.99% * 1/4 - (30px - 30px * 1/4))}.tabs--vertical__list:nth-child(n){float:left;margin-right:30px;clear:none}.tabs--vertical__list:last-child,.tabs--vertical__list:nth-child(4n){margin-right:0}.tabs--vertical__list:nth-child(4n+1){clear:left}.tabs--vertical__tab{padding:0;margin:0;display:block;vertical-align:top;position:relative;top:3px;font-size:1.5625rem;text-align:center;background-color:#fff}.tabs--vertical__tab--active{z-index:100;font-weight:400;background-color:#fff}.tabs--vertical__tab--active:after,.tabs--vertical__tab--active:before{content:"";position:absolute;width:50%;bottom:0;border-bottom:3px solid #6443a4}.tabs--vertical__tab--active:before{left:0}.tabs--vertical__tab--active:after{left:50%}.tabs--vertical__link{display:block;padding:.84375rem;text-decoration:none}.tabs--vertical__link:active,.tabs--vertical__link:focus,.tabs--vertical__link:hover,.tabs--vertical__link:link,.tabs--vertical__link:visited{color:#333;text-decoration:none;outline:0}.tabs--vertical__link:active,.tabs--vertical__link:focus,.tabs--vertical__link:hover{color:#6443a4}.tabs--vertical__content{display:block;width:calc(99.99% * 3/4 - (30px - 30px * 3/4))}.tabs--vertical__content:nth-child(n){float:left;margin-right:30px;clear:none}.tabs--vertical__content:last-child,.tabs--vertical__content:nth-child(4n){margin-right:0}.tabs--vertical__content:nth-child(4n+1){clear:left}.tabs--vertical__panel{display:none;width:100%;background:#fff}.tabs--vertical__panel:after,.tabs--vertical__panel:before{content:'';display:table}.tabs--vertical__panel:after{clear:both}.tabs--vertical__panel--current{display:block}
```
